name: Deployment Pipeline

on:
  workflow_run:
    workflows: ["Data Pipeline"]
    types:
      - completed

jobs:
  filler_job:
    runs-on: ubuntu-latest
    steps:
      - name: filler_job
        run: hostname

  build-and-push-image:
    runs-on: ubuntu-latest
    # needs: train
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # - name: Download artifacts
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: trained-model-artifacts
      #     path: artifacts/

      - name: Build and push Docker image
        env:
          DOCKER_REGISTRY: ankit100ni.azurecr.io  # Replace with your ACR URL
          IMAGE_NAME: ml-flask-app:latest
          IMAGE_TAG: latest
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker login $DOCKER_REGISTRY -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Azure AKS set context
        run: az aks get-credentials --resource-group mlops_dep --name mlops

      - name: Deploy to AKS
        run: kubectl apply -f deployment.yaml
