name: Deployment Pipeline

on:
  workflow_run:
    workflows: ["Data Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Download artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: static-site
      # - name: Test artifacts Download
      #   run: ls -R; date

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        env:
          DOCKER_REGISTRY: ankit100ni.azurecr.io
          IMAGE_NAME: ml-flask-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker login $DOCKER_REGISTRY -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker push $DOCKER_REGISTRY/$IMAGE_NAME:$IMAGE_TAG

      - name: Azure AKS set context
        run: az aks get-credentials --resource-group mlops_dep --name mlops

      - name: Deploy to AKS
        run: kubectl apply -f deployment.yaml
